spring:
  application:
    name: shopping-cart-backend

  profiles:
    active: dev

server:
  port: 8080

logging:
  level:
  
    root: INFO
    "[com.basil.shoppingcart]": DEBUG
    "[org.springframework.security]": INFO
    "[org.hibernate.SQL]": DEBUG

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha



app:
  jwt:
    secret: 7P2mV9QxL4nF8sR1aB6tY3uK5wE0iZ7cH2dN9pQ4vX8jM1oL6kR3sT5uY7wA9bC
    expiration: 86400000

  cors:
    allowed-origins:
      - http://localhost:5173
      - http://localhost:3000