spring:

  datasource:

    url: jdbc:mysql://localhost:3306/shopping_cart_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata

    username: root

    password: root

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:

    hibernate:
      ddl-auto: update

    show-sql: true

    properties:

      hibernate:

        "[format_sql]": true

        dialect: org.hibernate.dialect.MySQLDialect

    open-in-view: false

  sql:

    init:
      mode: never

  
  mail:
    host: smtp.gmail.com
    port: 587
    username: basilpaulose58@gmail.com
    password: basilpaulose58@123

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true